# Site settings
title: 木子说
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "学习、思考、感悟、成长"  
baseurl: ""
url: "http://www.libaoyi.cn"  

# About/contact
owner: 
  name: " libaoyi"
  email: libaoyi@163.com
  bio: "木子说"

# Data
gavatar: img/favicon1.ico
favicon: img/favicon1.ico

# douban_username: 
# twitter_username: libaoyi
# github_username: libaoyi
# facebook_username: 
# weibo_username: libaoyi
# zhihu_username: feat

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "libaoyi"
      header-img: "img/Xacebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
#gitment
# comment_gitment_repo: libaoyi.github.io
# comment_gitment_clientId: 5b68ff043472fa385239
# comment_gitment_clientSecret: d3818d7f9352e8adb1a8d548f3f7708ec1e39e18

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
